sudo: false
language: node_js
env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox
node_js:
  - node
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
